-- EXPLORATORY DATA ANALYSIS
-- TOTAL NO.OF RECORDS
SELECT COUNT(*) FROM flights_staging;

-- MACRO BASELINE ANALYSIS
-- TOTAL NO.OF DISTINCT AIRLINES AND THERE CODES
SELECT COUNT(DISTINCT AIRLINE) FROM flights_staging;
SELECT DISTINCT AIRLINE FROM flights_staging;

-- EARLIER FLIGHT DATE AND LATEST FLIGHT DATE
SELECT MIN(flight_date),MAX(flight_date) FROM flights_staging;

-- NO.OF CANCELLED FLIGHTS
SELECT COUNT(*) FROM flights_staging
WHERE CANCELLED=1;

-- CANCELLATION RATE
SELECT ROUND((SUM(CANCELLED=1)/COUNT(*))*100,2) FROM flights_staging;

-- OVERALL DELAY STATISTICS
SELECT ROUND(AVG(DEPARTURE_DELAY),2),ROUND(AVG(ARRIVAL_DELAY),2) FROM flights_staging;

SELECT air.AIRLINE,COUNT(*),ROUND(AVG(fli.DEPARTURE_DELAY),2) AS AVG_DEP_DELAY,ROUND(AVG(fli.ARRIVAL_DELAY),2) AS AVG_ARR_DELAY
FROM flights_staging AS fli
LEFT JOIN airlines AS air
ON fli.AIRLINE=air.IATA_CODE
GROUP BY fli.AIRLINE,air.AIRLINE
ORDER BY AVG_DEP_DELAY DESC,AVG_ARR_DELAY DESC;

SELECT air.AIRLINE,COUNT(*) AS TOTAL_SCHEDULED_FLIGHTS,SUM(fli.CANCELLED=1) AS TOTAL_CANCELLED_FLIGHTS,ROUND((SUM(fli.CANCELLED=1)/COUNT(*))*100,2) AS CANCELLATION_RATE
FROM flights_staging AS fli
LEFT JOIN airlines AS air
ON fli.AIRLINE=air.IATA_CODE
GROUP BY fli.AIRLINE,air.AIRLINE
ORDER BY CANCELLATION_RATE DESC;

-- GEOGRAPHIC & AIRPORT BOTTLENECKS
-- Origin & Destination delay bottlenecks (10k+ volume filter)
SELECT fli.ORIGIN_AIRPORT,air.AIRPORT,air.CITY,air.STATE,COUNT(*) AS TOTAL_OUTBOUND_FLIGHTS,ROUND(AVG(fli.DEPARTURE_DELAY),2) AS AVG_DEP_DELAY
FROM flights_staging AS fli
LEFT JOIN airports AS air
ON fli.ORIGIN_AIRPORT=air.IATA_CODE
GROUP BY fli.ORIGIN_AIRPORT,air.AIRPORT,air.CITY,air.STATE
HAVING COUNT(*) >=10000
ORDER BY AVG_DEP_DELAY DESC
LIMIT 20;

SELECT fli.DESTINATION_AIRPORT,air.AIRPORT,air.CITY,air.STATE,COUNT(*) AS TOTAL_INBOUND_FLIGHTS,ROUND(AVG(fli.ARRIVAL_DELAY),2) AS AVG_ARR_DELAY
FROM flights_staging AS fli
LEFT JOIN airports AS air
ON fli.DESTINATION_AIRPORT=air.IATA_CODE
GROUP BY fli.DESTINATION_AIRPORT,air.AIRPORT,air.CITY,air.STATE
HAVING COUNT(*) >=10000
ORDER BY AVG_ARR_DELAY DESC
LIMIT 10;

-- TEMPORAL TREND ANALYSIS
-- Performance patterns by Month and Day of Week (DAYOFWEEK)
SELECT MONTH(fli.FLIGHT_DATE) AS flight_month,COUNT(*) AS total_flights,SUM(fli.CANCELLED = 1) AS total_cancelled_flights,ROUND((SUM(fli.CANCELLED = 1)/ COUNT(*))*100, 2) AS cancellation_rate,ROUND(AVG(fli.ARRIVAL_DELAY), 2) AS avg_arrival_delay
FROM flights_staging AS fli
GROUP BY MONTH(fli.FLIGHT_DATE)
ORDER BY flight_month ASC;

SELECT DAYOFWEEK(fli.FLIGHT_DATE) AS flight_week,COUNT(*) AS total_scheduled_flights,ROUND(AVG(fli.DEPARTURE_DELAY),2) AS AVG_DEP_DELAY,ROUND(AVG(fli.ARRIVAL_DELAY),2) AS AVG_ARR_DELAY,ROUND((SUM(fli.CANCELLED = 1)/ COUNT(*))*100, 2) AS cancellation_rate
FROM flights_staging AS fli
GROUP BY DAYOFWEEK(fli.FLIGHT_DATE)
ORDER BY flight_week ASC;

-- ROUTE & DISTANCE METRICS
SELECT 
	(CASE
		WHEN DISTANCE<500 THEN 'Short Haul'
        WHEN DISTANCE<=1500 THEN 'Medium Haul'
        WHEN DISTANCE<=3000 THEN 'Long Haul'
        ELSE 'Ultra Long Haul'
	END) AS DISTANCE_BUCKET,COUNT(*) AS total_scheduled_flights,ROUND(AVG(fli.ARRIVAL_DELAY),2) AS AVG_ARR_DELAY,ROUND((SUM(fli.CANCELLED = 1)/ COUNT(*))*100, 2) AS cancellation_rate
FROM flights_staging AS fli
GROUP BY DISTANCE_BUCKET
ORDER BY AVG_ARR_DELAY DESC;
    
SELECT 
    fli.ORIGIN_AIRPORT,
    fli.DESTINATION_AIRPORT,
    COUNT(*) AS total_flights,
    ROUND(AVG(fli.DISTANCE), 0) AS avg_distance_miles,
    ROUND(AVG(fli.ARRIVAL_DELAY), 2) AS avg_arrival_delay
FROM flights_staging AS fli
GROUP BY fli.ORIGIN_AIRPORT, fli.DESTINATION_AIRPORT
ORDER BY total_flights DESC
LIMIT 10;